// generated by scripts/build-changelog.ts from RELEASE.md; edit RELEASE.md instead
export const CHANGELOG_VERSION = "0.3.3";
export const CHANGELOG_MARKDOWN = `# bcp v0.3.3

## Changelog, in the app

The app now carries its own changelog. After an update it opens a window with the release notes for the version that just landed, and when a newer desktop build is available the notes show up in the update banner before you install.

The Changelog button in the sidebar opens the same notes at any time. The notes are written once, before each release, and reused everywhere: they fill this window, the update banner, and the release page on GitHub, so nothing lives in two places.

## Shipped polish

- The app icon renders sharply again in the browser and installed surfaces after the favicon set was regenerated from the master artwork.
- The sidebar's toolbar and footer buttons now sit at even heights, and the footer buttons' hover fill no longer crowds the strip edge to edge.

**Full Changelog**: <https://github.com/Vittv/bcp/compare/v0.3.2...v0.3.3>`;
