// generated by scripts/build-changelog.ts from RELEASE.md; edit RELEASE.md instead
export const CHANGELOG_VERSION = "0.3.4";
export const CHANGELOG_MARKDOWN = `## Shipped polish

- The sidebar and Settings drop their group headings in favour of a hairline between groups, and the active row is marked by colour alone now, without a background fill.
- The Changelog window's typography was retuned, and its header no longer repeats the version the release already shows.
- The Daily Office bar lines up with the other pages again.

**Full Changelog**: <https://github.com/Vittv/bcp/compare/v0.3.3...v0.3.4>
`;
