// generated by scripts/build-changelog.ts from RELEASE.md; edit RELEASE.md instead
export const CHANGELOG_VERSION = "0.4.0";
export const CHANGELOG_MARKDOWN = `## The Apocrypha

The fifteen deuterocanonical books now have their own place in the sidebar, below the New Testament, and read like any other part of the Bible: a book picker, a chapter picker, and the arrows at the foot of every chapter. Tobit, Judith, Wisdom, Sirach, Baruch, the four Maccabees, both Esdras, the Greek Esther and Daniel, the Prayer of Manasses and Psalm 151 are all browsable, in the World English Bible's own order of books.

These exist only in the World English Bible, so that page carries no translation picker. They are also a scope of their own in the global search, under their own heading, so "sirach" or "apocrypha" lists them without crowding out the sixty-six books that get cited every day. Only six of the fifteen are ever read by the Lectionary; the rest are there because they belong to the set.

## Reading progress

The Bible reader now remembers how far through each book you have been. Every scripture row in the sidebar names the chapter you left off in, each book in the picker carries its own count, and Settings keeps a running total with a single Reset that clears both the counts and the places you stopped.

The Apocrypha counts toward that total, which moves the denominator to 1,402 chapters. A scripture row you have never opened still names the chapter it would take you to, so it never sits blank.

**Full Changelog**: <https://github.com/Vittv/bcp/compare/v0.3.4...v0.4.0>
`;
