#!/usr/bin/env bun
/**
 * Vendor the per-release notes into the app bundle.
 *
 * RELEASE.md is the single source of truth for a release: the very file that
 * becomes the GitHub release body. This script also copies it into
 * src/lib/changelog.ts so the in-app Changelog modal renders the same notes
 * offline, on every platform. The release recipe always runs it after the
 * version bump, and check-changelog-sync keeps the two from drifting.
 *
 * RELEASE.md shape (the same grammar the modal renders):
 *   - a `# bcp vX.Y.Z` title line (drives CHANGELOG_VERSION)
 *   - `## ` and `### ` sections, prose paragraphs, `- ` bullets
 *   - a trailing `**Full Changelog**: <url>` link
 *
 * Usage: bun scripts/build-changelog.ts
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const RELEASE_PATH = join(ROOT, "RELEASE.md");
const OUT_PATH = join(ROOT, "src/lib/changelog.ts");

const TITLE_VERSION = /^# .*?v(\d+\.\d+\.\d+)/;
const FULL_CHANGELOG = /^\*\*Full Changelog\*\*:/m;

function fail(message: string): never {
  console.error(`error: ${message}`);
  process.exit(1);
}

// escape a template literal body: backslashes, backticks and `${` all land
// verbatim in the generated module
function escapeTemplate(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

export async function buildChangelog(): Promise<void> {
  const notes = await readFile(RELEASE_PATH, "utf8");

  const title = notes.match(TITLE_VERSION);
  if (!title) {
    fail("RELEASE.md must start with a `# bcp vX.Y.Z` title line");
  }
  if (!FULL_CHANGELOG.test(notes)) {
    fail(
      "RELEASE.md must end with a `**Full Changelog**: <url>` line, the link the modal shows",
    );
  }
  const version = title[1];

  // SAFETY: package.json always carries a string version field; parsed only
  // to warn when the title and the bump have drifted (check-changelog-sync
  // fails in the release gate).
  const pkg = JSON.parse(
    await readFile(join(ROOT, "package.json"), "utf8"),
  ) as { version?: string };
  if (pkg.version && pkg.version !== version) {
    console.warn(
      `warning: RELEASE.md says v${version} but package.json is ${pkg.version}; ` +
        "run the release bump first or update the title",
    );
  }

  const source = [
    "// generated by scripts/build-changelog.ts from RELEASE.md; edit RELEASE.md instead",
    `export const CHANGELOG_VERSION = "${version}";`,
    `export const CHANGELOG_MARKDOWN = \`${escapeTemplate(notes)}\`;`,
    "",
  ].join("\n");

  await writeFile(OUT_PATH, source);
  console.log(`✓ v${version} notes vendored into ${OUT_PATH}`);
}

if (import.meta.main) {
  buildChangelog().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
