#!/usr/bin/env python3
"""Apply authoritative-text patches to the E-text extracted collects.

The patch operations are generated by gen_patches.py (patches.json), which
derives every corrected collect from the printed 2007 BCP (pdf_reference.json)
with Wikisource as the clean-transcription source where the PDF extraction
carries line-break artifacts. Patches are keyed by (rite, subsection, title):

  - REPLACE:  replace the text with the authoritative collect text
  - INSERT:   insert a missing collect before a given title
  - FIXTITLE: correct the title only

Reads and writes scratch-directory artifacts; see paths.py.
"""
import json

from paths import SCRATCH

BASE = SCRATCH / "collects.json"
PATCHES = SCRATCH / "patches.json"
OUT = SCRATCH / "collects_patched.json"

PATCHES_DATA = json.load(open(PATCHES))


# ---------------------------------------------------------------------------
# Holy-day titles (the <Holy Days> header is missing from the contemporary
# section of the e-text, so they were parsed into church-year).
# ---------------------------------------------------------------------------
HOLY_DAY_TITLES = [
    "Saint Andrew", "Saint Thomas", "Saint Stephen", "Saint John",
    "The Holy Innocents", "Confession of Saint Peter", "Conversion of Saint Paul",
    "The Presentation", "Saint Matthias", "Saint Joseph", "The Annunciation",
    "Saint Mark", "Saint Philip and Saint James", "The Visitation", "Saint Barnabas",
    "The Nativity of Saint John the Baptist", "Saint Peter and Saint Paul",
    "Independence Day", "Saint Mary Magdalene", "Saint James", "The Transfiguration",
    "Saint Mary the Virgin", "Saint Bartholomew", "Holy Cross Day", "Saint Matthew",
    "Saint Michael and All Angels", "Saint Luke", "Saint James of Jerusalem",
    "Saint Simon and Saint Jude", "All Saint's Day", "Thanksgiving Day",
]


def reorganize_contemporary(d):
    """Move holy days out of contemporary church-year into holy-days."""
    if "holy-days" in d["contemporary"]:
        return
    hd, cy = [], []
    for c in d["contemporary"]["church-year"]:
        (hd if c["title"] in HOLY_DAY_TITLES else cy).append(c)
    d["contemporary"]["church-year"] = cy
    d["contemporary"]["holy-days"] = hd


def key(rite, sub, title):
    return f"{rite}|{sub}|{title}"


d = json.load(open(BASE))
reorganize_contemporary(d)

# REPLACE
replaced = []
for k, text in PATCHES_DATA["REPLACE"].items():
    rite, sub, title = k.split("|", 2)
    for c in d[rite][sub]:
        if c["title"] == title:
            c["text"] = text
            c["patched"] = True
            replaced.append(k)
            break
    else:
        print(f"!! REPLACE target not found: {k}")

# FIXTITLE
for k, new in PATCHES_DATA["FIXTITLE"].items():
    rite, sub, old = k.split("|", 2)
    for c in d[rite][sub]:
        if c["title"] == old:
            c["title"] = new
            break

# INSERT
inserted = []
for k, items in PATCHES_DATA["INSERT"].items():
    rite, sub = k.split("|", 1)
    for title, spec in items.items():
        lst = d[rite][sub]
        pos = next((i for i, c in enumerate(lst) if c["title"] == spec["before"]), None)
        if pos is None:
            print(f"!! INSERT anchor not found: {k} before {spec['before']}")
            continue
        lst.insert(pos, {"title": title, "text": spec["text"], "notes": None, "line": None, "patched": True})
        inserted.append(f"{k}|{title}")

json.dump(d, open(OUT, "w"), indent=1)
print(f"replaced={len(replaced)} inserted={len(inserted)}")

# summary
for rite in d:
    print("==", rite)
    for sub, lst in d[rite].items():
        print(f"   {sub}: {len(lst)} collects")
